const TYPES = {
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  CHANGE_STATUS: "CHANGE_STATUS",
  EDIT_STATUS: 'EDIT_STATUS',
  EDIT_TASK: 'EDIT_TASK',
  ADD_ALL_TASK: 'ADD_ALL_TASK',
  ADD_TASK_SAGA: 'ADD_TASK_SAGA',
  DELETE_TASK_SAGA: "DELETE_TASK_SAGA",
  CHANGE_STATUS_SAGA: "CHANGE_STATUS_SAGA",
  EDIT_STATUS_SAGA: 'EDIT_STATUS_SAGA',
  EDIT_TASK_SAGA: 'EDIT_TASK_SAGA',
}

export default TYPES
